// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckjljmrieqihgbiqmyfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNramxqbXJpZXFpaGdiaXFteWZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwMDIyNzUsImV4cCI6MjA5MTU3ODI3NX0.90Xyp36Ehu2c7EmaSldH_WDGLT2jW_T3D0PXFp4o-2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});