import type { ReactNode } from 'react';
import { ArrowRight, Check, ChevronRight, MapPin, MessageCircle, Phone } from 'lucide-react';
import Header from '@/components/Header';
import { Footer } from '@/components/Footer';
import ProtectionProjects from '@/components/ProtectionProjects';
import { formatVerifiedStartingPrice } from '@/lib/verified-pricing';
import { LocalizedLink as Link } from '@/components/LocalizedLink';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { useSeo } from '@/hooks/use-seo';
import { buildBreadcrumb, buildService, buildWebPage, pageGraph, SITE_URL } from '@/lib/schema';
import { brands } from '@/data/brands';
import { CERAMIC_PATH, CERAMIC_TITLE, CERAMIC_DESCRIPTION, CERAMIC_H1, ceramicBrands, ceramicBenefits, ceramicOptions, ceramicProcess, ceramicFaqs, ceramicStartingPrice } from '@/data/ceramicCoatingContent';

const url = `${SITE_URL}${CERAMIC_PATH}`;
const hero = '/images/ceramic-coating/black-mercedes-finish-1024.webp';
const whatsapp = `https://wa.me/97143402223?text=${encodeURIComponent('Hi DIGI-TEC, I would like a ceramic coating quote. Please help me choose the preparation and surfaces for my car.\nMake/model: \nYear: \nPaint condition or concerns: ')}`;
const relatedBrands = ceramicBrands.map((name) => brands.find((brand) => brand.name === name)).filter(Boolean);
const graph = pageGraph([
  buildWebPage({ url, name: CERAMIC_TITLE, description: CERAMIC_DESCRIPTION, breadcrumbId: `${url}#breadcrumb`, primaryImage: hero, mainEntityId: `${url}#service`, dateModified: '2026-09-08' }),
  buildBreadcrumb(url, [{ name: 'Home', url: '/' }, { name: 'Services', url: '/services' }, { name: 'Ceramic Coating', url }]),
  buildService({ url, name: CERAMIC_H1, serviceType: 'Automotive ceramic coating', description: 'DIGI-TEC Performance Center offers ceramic coating in Al Quoz Industrial Area 3, Dubai. Paint preparation, product choice and optional wheel, trim or glass coverage are confirmed in the estimate.', image: hero }),
]);

function Quote({ placement, children = 'Get Ceramic Coating Quote' }: { placement: string; children?: ReactNode }) {
  // Normal anchors use the existing delegated GTM/GA4 contact tracker once.
  return <a className="cc-button cc-primary" href={whatsapp} target="_blank" rel="noopener noreferrer" data-cta-placement={`ceramic_${placement}`}><MessageCircle size={19} aria-hidden="true" />{children}</a>;
}

export default function CeramicCoatingPage() {
  useSeo({ title: CERAMIC_TITLE, description: CERAMIC_DESCRIPTION, canonical: url, jsonLd: graph });
  return (
    <div className="ceramic-page site-page min-h-screen bg-black text-off-white">
      <Header />
      <main id="ceramic-main">
        <section className="cc-hero theme-dark-section" aria-labelledby="ceramic-heading">
          <div className="cc-hero-copy">
            <nav className="cc-breadcrumb" aria-label="Breadcrumb"><Link to="/">Home</Link><ChevronRight size={14} aria-hidden="true" /><Link to="/services">Services</Link><ChevronRight size={14} aria-hidden="true" /><span aria-current="page">Ceramic Coating</span></nav>
            <p className="cc-kicker">DIGI-TEC Performance Center · Al Quoz</p>
            <h1 id="ceramic-heading">Ceramic Coating Dubai</h1>
            <p className="cc-hero-lead">A considered finish.<br />Care that goes beyond the shine.</p>
            <p>Professional ceramic coating for luxury and performance cars, with paint preparation and surface coverage matched to your vehicle. Discuss gloss, easier cleaning and the right care plan with our Dubai workshop.</p>
            <div className="cc-actions"><Quote placement="hero" /><a className="cc-button cc-secondary" href="tel:+97143402223" data-cta-placement="ceramic_hero"><Phone size={18} aria-hidden="true" />Call the workshop</a></div>
            <a className="cc-text-link" href="#ceramic-options">Explore coating options <ArrowRight size={16} aria-hidden="true" /></a>
          </div>
          <figure className="cc-hero-visual"><img src={hero} srcSet="/images/ceramic-coating/black-mercedes-finish-640.webp 640w, /images/ceramic-coating/black-mercedes-finish-1024.webp 1024w" sizes="(min-width: 1000px) 48vw, 100vw" width={1024} height={1536} alt="Black Mercedes-Benz G-Class with ceiling lights reflected across its bonnet and bodywork" loading="eager" /><figcaption>Paint finish detail</figcaption></figure>
        </section>

        <div className="cc-trust" aria-label="Verified workshop and service information"><div><MapPin aria-hidden="true" size={19} /><span><strong>Al Quoz Industrial Area 3</strong>Dubai workshop</span></div><div><Check aria-hidden="true" size={19} /><span><strong>Preparation & coating</strong>Scope agreed for your car</span></div><div><Check aria-hidden="true" size={19} /><span><strong>Luxury & performance vehicles</strong>Independent workshop care</span></div></div>
        <nav className="cc-jump" aria-label="On this page"><a href="#ceramic-benefits">Benefits</a><a href="#ceramic-preparation">Preparation</a><a href="#ceramic-options">Options</a><a href="#ceramic-cost">Price & quote</a><a href="#ceramic-comparison">Compare with PPF</a><a href="#ceramic-faq">FAQs</a></nav>

        <section className="cc-section cc-split" aria-labelledby="ceramic-definition"><div><p className="cc-kicker">Understand the treatment</p><h2 id="ceramic-definition">What Is Ceramic Coating?</h2></div><div><p>Ceramic coating is a protective treatment applied to automotive paint and other compatible surfaces. It can improve water behaviour, gloss and resistance to certain contaminants, helping maintain the appearance of properly prepared paint.</p><p>The term <strong>nano ceramic coating</strong> is often used for this category of surface treatment. The actual product, preparation and maintenance determine its properties.</p><p className="cc-callout"><strong>Coating does not make paint scratch-proof.</strong> It does not remove existing defects or provide the physical stone-chip barrier of paint protection film.</p></div></section>

        <section id="ceramic-benefits" className="cc-section cc-panel" aria-labelledby="ceramic-benefits-heading"><div className="cc-section-intro"><p className="cc-kicker">What changes at the surface</p><h2 id="ceramic-benefits-heading">Ceramic Coating Benefits</h2><p>The aim is a well-prepared finish that is easier to care for. The selected coating determines the level and type of protection.</p></div><div className="cc-benefits">{ceramicBenefits.map((benefit, index) => <article key={benefit.title}><span className="cc-number">0{index + 1}</span><h3>{benefit.title}</h3><p>{benefit.text}</p></article>)}</div></section>

        <section className="cc-section cc-split" aria-labelledby="ceramic-dubai"><div><p className="cc-kicker">Local conditions. Practical care.</p><h2 id="ceramic-dubai">Why Ceramic Coating Makes Sense in Dubai</h2></div><div><p>Dust, sand and road contamination quickly collect on a regularly driven car in Dubai. Frequent washing makes the way you clean the surface important: a suitable coating can help dirt release, but rubbing dusty paint can still create marks.</p><p>Heat and strong sunlight make care and product selection relevant too. Wash and dry in suitable conditions, and follow the coating’s guidance rather than allowing dirty water to dry on hot panels. UV and environmental-resistance properties must be checked for the actual product.</p><p>For a premium vehicle, ceramic paint protection is part of an ongoing care routine. It does not completely prevent sun damage, sand abrasion, water spotting or scratches.</p></div></section>

        <section id="ceramic-preparation" className="cc-section cc-panel cc-split" aria-labelledby="ceramic-preparation-heading"><div><p className="cc-kicker">The finish starts underneath</p><h2 id="ceramic-preparation-heading">Preparing Your Car for Ceramic Coating</h2><Link className="cc-text-link" to="/services/car-polishing-dubai">Explore paint correction & paint care <ArrowRight size={16} aria-hidden="true" /></Link></div><div><p>Coating follows the surface underneath it. Existing swirls, haze and scratches remain visible if they are not addressed first. Applying a coating over poorly prepared paint can mean that further preparation and reapplication are needed to achieve the finish you wanted.</p><p>DIGI-TEC assesses the paint and confirms preparation in the estimate. Decontamination and polishing or paint correction can form part of the agreed scope where appropriate; every vehicle does not need the same amount of correction.</p><ul className="cc-check-list"><li><Check aria-hidden="true" />Review paint condition, previous repairs and existing protection</li><li><Check aria-hidden="true" />Agree washing, decontamination and surface preparation</li><li><Check aria-hidden="true" />Discuss correction only where the paint and desired result justify it</li><li><Check aria-hidden="true" />Confirm the coating, treated surfaces and care requirements</li></ul></div></section>

        <section className="cc-section" aria-labelledby="ceramic-process"><p className="cc-kicker">From assessment to aftercare</p><h2 id="ceramic-process">Our Ceramic Coating Process</h2><p className="cc-section-intro">The exact preparation, application and curing schedule depend on the chosen coating system and your car. These are the stages to review with the workshop.</p><ol className="cc-process">{ceramicProcess.map((step, index) => <li key={step.title}><span className="cc-number">0{index + 1}</span><h3>{step.title}</h3><p>{step.text}</p></li>)}</ol></section>

        <section id="ceramic-options" className="cc-section cc-panel" aria-labelledby="ceramic-options-heading"><div className="cc-section-intro"><p className="cc-kicker">Choose the scope, then the product</p><h2 id="ceramic-options-heading">Ceramic Coating Options</h2><p>Start with the painted surfaces, then discuss additional coverage or compatible PPF. Preparation, product choice, any layer schedule and product terms are confirmed in the quotation.</p></div><div className="cc-options">{ceramicOptions.map((option) => <article key={option.title}><p className="cc-kicker">{option.label}</p><h3>{option.title}</h3><p>{option.text}</p><p className="cc-small">{option.detail}</p></article>)}</div><div className="cc-actions"><Quote placement="options">Get the Right Coating Option for Your Car</Quote></div></section>

        <section className="cc-section cc-workshop" aria-labelledby="ceramic-workshop-heading"><figure><img src="/images/ceramic-coating/workshop-vehicles-960.webp" srcSet="/images/ceramic-coating/workshop-vehicles-540.webp 540w, /images/ceramic-coating/workshop-vehicles-960.webp 960w" sizes="(min-width: 900px) 44vw, 100vw" width={960} height={1280} loading="lazy" decoding="async" alt="Porsche cars parked in DIGI-TEC’s workshop with a BMW on a lift behind them" /><figcaption>Inside the DIGI-TEC workshop. This photograph shows workshop vehicles; it is not a documented ceramic-coating before-and-after.</figcaption></figure><div><p className="cc-kicker">See the workshop behind the service</p><h2 id="ceramic-workshop-heading">Why Choose DIGI-TEC for Ceramic Coating in Dubai?</h2><p>DIGI-TEC Performance Center is an independent automotive workshop in Al Quoz, serving luxury and performance vehicles. Ceramic coating sits alongside paint correction, PPF and bodywork, so paint condition can be considered before protection is selected.</p><p>The estimate identifies the proposed coating, preparation and covered surfaces. That helps you compare the scope of work and understand the care it will need.</p><h3>What to look for in real coating work</h3><p>Ask to see recent work relevant to your car and finish. Compare paint condition before preparation with the finished result under similar lighting, and ask which surfaces and preparation were included.</p><div className="cc-actions"><Quote placement="workshop">Ask About Ceramic Coating</Quote><Link className="cc-text-link" to="/about">About DIGI-TEC <ArrowRight size={16} aria-hidden="true" /></Link></div></div></section>

        <ProtectionProjects service="ceramic" className="cc-section" />

        <section id="ceramic-cost" className="cc-section cc-panel cc-split" aria-labelledby="ceramic-cost-heading"><div><p className="cc-kicker">Price follows preparation & scope</p><h2 id="ceramic-cost-heading">How Much Does Ceramic Coating Cost in Dubai?</h2>{formatVerifiedStartingPrice(ceramicStartingPrice) && <p className="cc-starting-price text-2xl font-semibold">{formatVerifiedStartingPrice(ceramicStartingPrice)}</p>}<Quote placement="price">Get an Exact Ceramic Coating Quote</Quote></div><div><p>Ceramic coating price in Dubai varies with the condition of the car and the work included. A vehicle needing paint correction has a different preparation scope from one with a finish ready for coating.</p><dl className="cc-price-factors"><div><dt>Vehicle size & surfaces</dt><dd>Painted area and any wheel, trim or glass coverage affect the work.</dd></div><div><dt>Paint condition</dt><dd>Contamination, swirls, previous repairs and existing protection influence preparation.</dd></div><div><dt>Correction required</dt><dd>Polishing or correction is assessed for the paint and desired finish.</dd></div><div><dt>Coating system</dt><dd>The selected product, application requirements and agreed coverage determine the coating scope.</dd></div></dl><p>Compare quotes using the same preparation, surfaces and product terms. Share your make, model, year and paint concerns to start the conversation; an inspection may be needed for an exact scope.</p><h3>What should your coating quote identify?</h3><p>Ask for the selected coating, the panels and additional surfaces included, the agreed preparation or correction, workshop time and product-specific curing and first-wash guidance. If PPF is already fitted, confirm compatibility separately. A quoted layer count alone does not describe the preparation, protection or maintenance required.</p></div></section>

        <section id="ceramic-comparison" className="cc-section" aria-labelledby="ceramic-comparison-heading"><p className="cc-kicker">Choose for the protection you need</p><h2 id="ceramic-comparison-heading">Ceramic Coating vs PPF</h2><p className="cc-section-intro">Coating focuses on surface behaviour and appearance. PPF provides a physical film over the panels it covers. The right choice depends on how you use and maintain your car.</p><div className="cc-table-wrap" role="region" aria-label="Ceramic coating and PPF comparison" tabIndex={0}><table><caption className="sr-only">Ceramic coating and paint protection film compared by purpose. Properties vary by product.</caption><thead><tr><th scope="col">Priority</th><th scope="col">Ceramic coating</th><th scope="col">Paint protection film</th></tr></thead><tbody>{[
          ['Physical protection', 'A bonded surface treatment', 'A replaceable physical film'],
          ['Stone chips', 'No meaningful stone-chip barrier', 'Can reduce small-impact damage on covered panels'],
          ['Water & cleaning', 'Can improve water behaviour and ease of cleaning', 'Depends on the film’s top surface or compatible coating'],
          ['Gloss & appearance', 'Can enhance properly prepared paint', 'Clear or sheen-changing film, subject to availability'],
          ['Contaminants', 'Resistance depends on the selected coating', 'Film properties and ongoing care determine resistance'],
          ['Paint preservation', 'Supports appearance and surface maintenance', 'Helps reduce some physical damage to covered paint'],
          ['Typical use', 'A finish that is easier to maintain', 'Impact-area or broader exterior protection'],
        ].map(([label, coating, film]) => <tr key={label}><th scope="row">{label}</th><td>{coating}</td><td>{film}</td></tr>)}</tbody></table></div><div className="cc-actions" aria-label="Related paint care services"><Link to="/services/paint-protection-film" className="cc-text-link">Explore PPF coverage in Dubai <ArrowRight size={16} aria-hidden="true" /></Link><Quote placement="comparison">Discuss Your Paint Protection Options</Quote></div><div className="cc-comparison-notes"><div><h3>Can PPF and ceramic coating be combined?</h3><p>Yes, suitable systems can work together. DIGI-TEC’s existing options include combined PPF and coating for compatible surfaces. Confirm the specific products, application order and care requirements before proceeding.</p></div><div><h3>Ceramic coating vs wax or sealant</h3><p>Traditional waxes and sealants are also used to improve appearance and water behaviour. Professional ceramic coating typically requires more deliberate preparation and product-specific curing. Product categories overlap, so compare the actual system and maintenance needs rather than assuming a fixed lifespan from the label.</p></div></div></section>

        <section className="cc-section cc-panel" aria-labelledby="ceramic-brands-heading"><p className="cc-kicker">Paint care around your car</p><h2 id="ceramic-brands-heading">Ceramic Coating for Luxury & Performance Cars in Dubai</h2><p className="cc-section-intro">Gloss, presentation and ease of maintenance can matter as much on a daily-driven luxury car as on a weekend performance car. Discuss the paint’s current condition and your care routine. Explore DIGI-TEC’s existing brand workshop pages, then confirm coating suitability for your model and finish.</p><div className="cc-brand-links">{relatedBrands.map((brand) => brand && <Link key={brand.slug} to={`/brands/${brand.slug}`}>{brand.name}<ArrowRight size={16} aria-hidden="true" /></Link>)}</div><p className="cc-small">DIGI-TEC is an independent workshop. Vehicle brand names do not imply manufacturer authorization.</p></section>

        <section id="ceramic-faq" className="cc-section" aria-labelledby="ceramic-faq-heading"><p className="cc-kicker">Before you book</p><h2 id="ceramic-faq-heading">Ceramic Coating Questions, Answered</h2><Accordion type="single" collapsible className="cc-faq">{ceramicFaqs.map((faq, index) => <AccordionItem key={faq.question} value={`ceramic-faq-${index}`}><AccordionTrigger>{faq.question}</AccordionTrigger><AccordionContent forceMount>{faq.answer}</AccordionContent></AccordionItem>)}</Accordion><div className="cc-actions"><Quote placement="faq">Check the Right Coating for Your Car</Quote></div></section>

        <section id="ceramic-contact" className="cc-section cc-contact cc-panel cc-split" aria-labelledby="ceramic-contact-heading"><div><p className="cc-kicker">Looking for ceramic coating near you?</p><h2 id="ceramic-contact-heading">Visit DIGI-TEC in Al Quoz</h2><address>DIGI-TEC Performance Center<br />Al Quoz Industrial Area 3<br />Dubai, UAE<br /><a href="tel:+97143402223" data-cta-placement="ceramic_contact">+971 4 340 2223</a><br /><a href="mailto:info@digitecme.com" data-cta-placement="ceramic_contact">info@digitecme.com</a></address></div><div><p>Share your vehicle details and paint-care priorities before visiting. The team can discuss the appropriate assessment and confirm appointment availability and current opening hours.</p><div className="cc-actions"><Quote placement="contact">WhatsApp DIGI-TEC</Quote><a className="cc-button cc-secondary" href="https://maps.google.com/?q=Al+Quoz+Industrial+Area+3+Dubai" target="_blank" rel="noopener noreferrer" data-cta-placement="ceramic_contact"><MapPin size={18} aria-hidden="true" />View workshop area</a></div><div className="cc-actions"><Link to="/services/paint-protection-dubai" className="cc-text-link">Compare paint-care options <ArrowRight size={16} aria-hidden="true" /></Link><Link to="/services" className="cc-text-link">Explore all workshop services <ArrowRight size={16} aria-hidden="true" /></Link></div><p className="cc-small cc-contact-note">WhatsApp opens a draft for you to review and send. <a href="/privacy-policy.pdf" target="_blank" rel="noopener noreferrer">Privacy policy</a></p></div></section>
      </main>
      <noscript><style>{'.cc-faq [role=region][data-state=closed] { display: block; animation: none; height: auto; overflow: visible; } .cc-faq button svg { display: none; }'}</style></noscript>
      <Footer />
      <nav className="cc-mobile-contact" aria-label="Ceramic coating contact shortcuts"><a href={whatsapp} target="_blank" rel="noopener noreferrer" data-cta-placement="ceramic_mobile"><MessageCircle size={19} aria-hidden="true" />WhatsApp quote</a><a href="tel:+97143402223" data-cta-placement="ceramic_mobile"><Phone size={19} aria-hidden="true" />Call</a></nav>
    </div>
  );
}
