import { ArrowRight, Camera, ChevronRight, MapPin, MessageCircle, Phone } from 'lucide-react';
import Header from '@/components/Header';
import { Footer } from '@/components/Footer';
import { LocalizedLink as Link } from '@/components/LocalizedLink';
import PaintAssessmentForm from '@/components/PaintAssessmentForm';
import PaintCorrectionProjects from '@/components/PaintCorrectionProjects';
import { useSeo } from '@/hooks/use-seo';
import { buildBreadcrumb, buildService, buildWebPage, pageGraph, SITE_URL } from '@/lib/schema';
import { brands } from '@/data/brands';
import { PAINT_CORRECTION_PATH, PAINT_CORRECTION_TITLE, PAINT_CORRECTION_H1, PAINT_CORRECTION_DESCRIPTION, PAINT_ASSESSMENT_HREF, PAINT_PHOTO_HREF, paintBrandNames, paintFaqs, paintProblems, paintServiceLevels } from '@/data/paintCorrectionContent';
import paintStyles from '@/styles/paint-correction.css?raw';

const url = `${SITE_URL}${PAINT_CORRECTION_PATH}`;
const heroImage = '/images/paint-correction/porsche-workshop-1200.webp';
const graph = pageGraph([
  buildWebPage({ url, name: PAINT_CORRECTION_TITLE, description: PAINT_CORRECTION_DESCRIPTION, breadcrumbId: `${url}#breadcrumb`, primaryImage: heroImage, mainEntityId: `${url}#service`, dateModified: '2026-09-08' }),
  buildBreadcrumb(url, [{ name: 'Home', url: '/' }, { name: 'Services', url: '/services' }, { name: 'Car Polishing & Paint Correction', url }]),
  buildService({ url, name: PAINT_CORRECTION_H1, serviceType: 'Car polishing and paint correction', description: 'DIGI-TEC Performance Center in Al Quoz Industrial Area 3, Dubai assesses vehicle paint condition and provides paint correction and related paint-care options. Preparation, correction scope and achievable finish are assessed for the vehicle.', image: heroImage }),
]);
const relevantBrands = paintBrandNames.map((name) => brands.find((brand) => brand.name === name)).filter(Boolean);

function ContactLink({ children = 'WhatsApp DIGI-TEC', placement, photo = false }: { children?: React.ReactNode; placement: string; photo?: boolean }) {
  return <a href={photo ? PAINT_PHOTO_HREF : PAINT_ASSESSMENT_HREF} target="_blank" rel="noopener noreferrer" data-cta-placement={`paint_${placement}`} className="paint-button paint-primary">{photo ? <Camera size={19} aria-hidden="true" /> : <MessageCircle size={19} aria-hidden="true" />}{children}</a>;
}

export default function PaintCorrectionPage() {
  useSeo({ title: PAINT_CORRECTION_TITLE, description: PAINT_CORRECTION_DESCRIPTION, canonical: url, hasArabicVersion: false, jsonLd: graph });
  return (
    <div className="paint-care-page min-h-screen bg-black text-off-white">
      {/* Page-scoped CSS is included in SSR HTML, so no shared prerender edit is needed. */}
      <style dangerouslySetInnerHTML={{ __html: paintStyles }} />
      <Header />
      <main id="paint-main">
        <section className="paint-hero theme-dark-section" aria-labelledby="paint-title">
          <div className="paint-hero-copy">
            <nav className="paint-breadcrumb" aria-label="Breadcrumb"><Link to="/">Home</Link><ChevronRight size={14} aria-hidden="true" /><Link to="/services">Services</Link><ChevronRight size={14} aria-hidden="true" /><span aria-current="page">Car Polishing &amp; Paint Correction</span></nav>
            <p className="paint-kicker">DIGI-TEC Performance Center / Dubai</p>
            <h1 id="paint-title">Car Polishing &amp; <span>Paint Correction</span> Dubai</h1>
            <p className="paint-hero-lead">Swirled, scratched or dull paint?</p>
            <p>Ask our Al Quoz workshop what polishing or paint correction can safely improve, with a quote based on your car’s condition.</p>
            <div className="paint-actions"><a href="#paint-assessment" className="paint-button paint-primary">Get Paint Assessment &amp; Quote <ArrowRight size={18} aria-hidden="true" /></a><a href={PAINT_ASSESSMENT_HREF} target="_blank" rel="noopener noreferrer" className="paint-button paint-secondary" data-cta-placement="paint_hero"><MessageCircle size={18} aria-hidden="true" />WhatsApp DIGI-TEC</a></div>
          </div>
          <figure className="paint-hero-photo"><img src={heroImage} srcSet="/images/paint-correction/porsche-workshop-640.webp 640w, /images/paint-correction/porsche-workshop-1200.webp 1200w" sizes="(min-width: 1000px) 47vw, 100vw" width={1200} height={1600} {...{ fetchpriority: 'high' }} alt="Rear of a white Porsche GT3 RS inside DIGI-TEC’s workshop" /><figcaption>Porsche GT3 RS at the DIGI-TEC workshop.<br />Workshop photograph; no correction result is claimed.</figcaption></figure>
        </section>

        <nav className="paint-overview-nav" aria-label="Explore paint care"><a href="#paint-problems"><span>01</span>Understand the marks</a><a href="#paint-comparison"><span>02</span>Choose the right approach</a><a href="#paint-pricing"><span>03</span>Plan your assessment</a></nav>

        <section className="paint-section paint-introduction" aria-labelledby="paint-definition-title"><div><p className="paint-kicker">Finish enhancement / Defect correction</p><h2 id="paint-definition-title">What Is Car Polishing?</h2><p>Car polishing uses a suitable polish and technique to improve clarity, gloss and certain surface imperfections. Machine polishing can refine a sound finish by removing a small amount of material where an abrasive polish is used.</p><p>It cannot replace missing paint, fill a stone chip, straighten a dent or repair peeling clear coat. The right starting point is the condition of your car’s finish.</p></div><div><h2>What Is Paint Correction?</h2><p>Paint correction is a more deliberate approach to improving assessed paint defects. Swirl marks, light scratches, haze and some water spotting or oxidation may be correctable, but no single process is right for every car.</p><p>Defect depth, clear-coat condition, previous repairs and the amount of material available for safe correction all matter. The goal is a suitable improvement while preserving the finish.</p></div></section>

        <section id="paint-problems" className="paint-section paint-soft" aria-labelledby="paint-problems-title"><div className="paint-heading-row"><div><p className="paint-kicker">Start with what you can see</p><h2 id="paint-problems-title">Paint Problems We Can Assess</h2></div><p>Strong Dubai sunlight can make fine marks obvious. Tell us when you notice them and whether the car has been repainted, polished or protected before.</p></div><div className="paint-problems">{paintProblems.map((problem, index) => <article key={problem.title}><span className="paint-number" aria-hidden="true">0{index + 1}</span><h3>{problem.title}</h3><p>{problem.appearance}</p><p>{problem.assessment}</p></article>)}</div></section>

        <section id="paint-scratches" className="paint-section paint-scratch-section" aria-labelledby="paint-scratches-title"><div><p className="paint-kicker">Scratch removal starts with depth</p><h2 id="paint-scratches-title">Can Car Scratches Be Polished Out?</h2><p>Some can. Very light clear-coat marks may improve with suitable polishing. Moderate scratches need a closer assessment: reducing their visibility may be safer than trying to remove them completely.</p><p>Deep scratches that reach beyond safely correctable layers may need touch-up or refinishing. Paint correction does not repair dents or replace paint lost to chips.</p><Link to="/services/car-body-repair-dubai" className="paint-link">Explore body and paint repair for deeper damage <ArrowRight size={16} aria-hidden="true" /></Link></div><aside className="paint-photo-prompt"><Camera size={32} aria-hidden="true" /><h3>Show us the scratch.</h3><p>Send one view of the affected panel and a closer photo from an angle that shows the mark. Mention any previous paintwork. Photos help us discuss the concern; an inspection may still be needed to judge depth and safe correction.</p><ContactLink placement="scratch_photo" photo>Send Us a Photo of the Scratch</ContactLink><p className="paint-note">Add the images directly in WhatsApp. There is no website photo upload.</p></aside></section>

        <section className="paint-section paint-split" aria-labelledby="paint-swirls-title"><div><p className="paint-kicker">Fine marks. Interrupted reflections.</p><h2 id="paint-swirls-title">Swirl Mark Removal in Dubai</h2></div><div><p>Swirl marks are fine scratches that become easy to see around a bright reflection. Dust trapped in wash materials, wiping dry paint or unsuitable previous polishing can leave these marks. Sunlight and inspection lighting make them more visible, particularly on dark colours.</p><p>Appropriate polishing or correction can often improve shallow swirls. Afterward, gentle washing, clean materials and avoiding dry dust removal help preserve the improvement. Repeated aggressive polishing is not a substitute for careful maintenance.</p></div></section>

        <section id="paint-comparison" className="paint-section paint-soft" aria-labelledby="paint-comparison-title"><p className="paint-kicker">The scope matters more than the label</p><h2 id="paint-comparison-title">Car Polishing vs Paint Correction</h2><p className="paint-intro">These terms overlap: polishing is a technique used in correction. The distinction below helps frame the result you want, without assuming your car needs the most intensive option.</p><div className="paint-table-wrap" role="region" aria-label="Car polishing and paint correction comparison" tabIndex={0}><table><caption className="sr-only">Typical focus of enhancement polishing compared with targeted paint correction</caption><thead><tr><th scope="col">Consideration</th><th scope="col">Polishing / paint enhancement</th><th scope="col">Paint correction</th></tr></thead><tbody>{[
          ['Purpose', 'Improve gloss and clarity; address suitable minor marks', 'Target assessed defects while respecting paint limits'],
          ['Vehicle condition', 'Sound paint mainly needing a fresher appearance', 'Swirls, scratches, haze or other defects needing closer assessment'],
          ['Process intensity', 'Chosen for the finish and desired enhancement', 'Chosen for defect depth, paint condition and safe correction'],
          ['Assessment', 'Check paint condition and previous work', 'Review the defects, previous work and achievable improvement'],
          ['Expected result', 'Improved appearance where the paint is suitable', 'Reduction of safely correctable defects; some marks may remain'],
          ['Time required', 'Confirmed from vehicle and agreed scope', 'Confirmed from preparation and correction required'],
          ['Protection afterward', 'Consider compatible coating or film and careful washing', 'Consider compatible coating or film and careful washing'],
        ].map(([label, polish, correction]) => <tr key={label}><th scope="row">{label}</th><td>{polish}</td><td>{correction}</td></tr>)}</tbody></table></div></section>

        <section className="paint-section paint-split" aria-labelledby="paint-inspection-title"><div><p className="paint-kicker">Preserve the paint you have</p><h2 id="paint-inspection-title">Professional Paint Assessment</h2></div><div><p>Begin with inspection, not an automatic correction package. DIGI-TEC assesses paint condition and preparation needs before a paint-care scope is agreed. Tell the team about repainting, previous correction and any existing film or coating.</p><p>Available paint thickness and clear-coat condition influence what can safely be corrected. Ask how suitability will be assessed for your car, what improvement is realistic and which marks should be left alone or repaired differently.</p><p>Matte or satin paint needs a different approach: conventional gloss polishing can change its appearance. Identify the finish before any correction is proposed.</p></div></section>

        <section id="paint-process" className="paint-section paint-process-section" aria-labelledby="paint-process-title"><p className="paint-kicker">From concern to agreed finish</p><h2 id="paint-process-title">Our Car Polishing &amp; Paint Correction Process</h2><p className="paint-intro">The exact preparation and correction method are agreed for the vehicle. The existing paint-care service is based on assessment, a defined scope and a product-appropriate finish.</p><ol className="paint-process">{[
          ['Discuss & inspect', 'Share the paint concerns, previous repairs and desired result. Photos can begin the conversation; suitability is assessed on the car.'],
          ['Agree preparation & scope', 'Review the required preparation, areas to be treated and realistic limits. Cleaning, contamination and existing protection affect the plan.'],
          ['Carry out the agreed correction', 'Polishing or correction is matched to the assessed finish and approved scope. More intensive work is not automatically the right choice.'],
          ['Review & plan protection', 'Review the finish and any remaining defects with the team. Discuss suitable care and whether ceramic coating or PPF fits your priorities.'],
        ].map(([title, description], index) => <li key={title}><span className="paint-number">0{index + 1}</span><h3>{title}</h3><p>{description}</p></li>)}</ol></section>

        <PaintCorrectionProjects />

        <section id="paint-pricing" className="paint-section paint-soft" aria-labelledby="paint-pricing-title"><div className="paint-heading-row"><div><p className="paint-kicker">Plan the work around your paint</p><h2 id="paint-pricing-title">How Much Does Car Polishing &amp; Paint Correction Cost in Dubai?</h2></div><p>Vehicle size, paint condition, defect severity, previous paintwork, preparation and the amount of correction required affect the quote. Protection afterward is a separate scope to discuss.</p></div><div className="paint-prices">{paintServiceLevels.map((level) => <article key={level.name}><h3>{level.name}</h3><p>{level.purpose}</p><p>{level.suitable}</p><p className="paint-price">{typeof level.fromAed === 'number' && Number.isFinite(level.fromAed) && level.fromAed > 0 && level.priceSource?.trim() ? `From AED ${level.fromAed.toLocaleString('en-AE')}` : 'Price based on vehicle & paint condition'}</p><a className="paint-link" href="#paint-assessment">{level.name === 'Car Polishing' ? 'Get an Exact Quote for Your Car' : 'Get Paint Assessment & Quote'} <ArrowRight size={18} aria-hidden="true" /></a></article>)}</div><p className="paint-note">These describe different objectives for assessment, not fixed stage-based packages or guaranteed levels of scratch removal.</p></section>

        <section id="paint-protection" className="paint-section" aria-labelledby="paint-protection-title"><p className="paint-kicker">After the improvement</p><h2 id="paint-protection-title">Protecting the Finish After Paint Correction</h2><ol className="paint-finish-flow" aria-label="Paint-care sequence"><li>Assess paint condition</li><li>Agree correction</li><li>Review the improved finish</li><li>Choose suitable protection</li></ol><div className="paint-protection-options" role="group" aria-label="Related paint care services"><article><h3>Should You Ceramic Coat After Paint Correction?</h3><p>A compatible ceramic coating may be considered once the paint has been prepared and its appearance improved. Depending on the product, it can support water beading, ease of cleaning and finish maintenance. It does not remove scratches or make the finish scratch-proof.</p><Link to="/services/ceramic-coating" className="paint-link">Explore ceramic coating <ArrowRight size={16} aria-hidden="true" /></Link></article><article><h3>Paint Correction Before PPF</h3><p>Film adds a physical barrier to covered panels, but it does not correct defects underneath. Paint condition, previous repairs and film compatibility should be assessed before installation. Discuss whether preparation or correction is appropriate before selecting coverage.</p><Link to="/services/paint-protection-film" className="paint-link">Explore paint protection film <ArrowRight size={16} aria-hidden="true" /></Link></article></div><p className="paint-intro">Careful washing remains part of the plan. Follow the chosen product’s care guidance, remove dust gently and ask about any new marks before attempting abrasive polishing yourself.</p></section>

        <section className="paint-section paint-soft paint-workshop" aria-labelledby="paint-why-title"><figure><img src="/images/paint-correction/workshop-floor-960.webp" srcSet="/images/paint-correction/workshop-floor-540.webp 540w, /images/paint-correction/workshop-floor-960.webp 960w" sizes="(min-width: 900px) 42vw, 100vw" width={960} height={1280} loading="lazy" decoding="async" alt="Luxury vehicles with DIGI-TEC plates parked in the workshop, including a Lamborghini SUV" /><figcaption>Inside the DIGI-TEC workshop in Al Quoz. Vehicle photograph, not a polishing before-and-after.</figcaption></figure><div><p className="paint-kicker">An independent Dubai workshop</p><h2 id="paint-why-title">Why Choose DIGI-TEC for Car Polishing &amp; Paint Correction?</h2><p>DIGI-TEC’s paint-care offering includes paint correction, ceramic coating and PPF, alongside body repair. That allows the discussion to start with the actual condition of your car and whether it needs correction, protection or a different repair.</p><ul className="paint-facts"><li>Paint condition and preparation assessed before the scope is agreed</li><li>Luxury and performance vehicle workshop experience</li><li>Related correction, bodywork and protection services</li><li>A workshop location in Al Quoz Industrial Area 3, Dubai</li></ul><p>Ask to see recent correction work relevant to your paint concerns and discuss what improvement is realistic for your car.</p><Link to="/about" className="paint-link">About DIGI-TEC Performance Center <ArrowRight size={16} aria-hidden="true" /></Link></div></section>

        <section className="paint-section" aria-labelledby="paint-brands-title"><p className="paint-kicker">Care for the finish, not just the badge</p><h2 id="paint-brands-title">Paint Correction for Luxury &amp; Performance Cars in Dubai</h2><p className="paint-intro">Original paint, repaired panels and special finishes need individual consideration. Owners of high-value cars may prefer a measured improvement that preserves the finish over chasing every mark. Explore DIGI-TEC’s existing brand workshop pages, then discuss the paint and history of your exact vehicle.</p><div className="paint-brands">{relevantBrands.map((brand) => brand && <Link key={brand.slug} to={`/brands/${brand.slug}`}>{brand.name}<ArrowRight size={16} aria-hidden="true" /></Link>)}</div><p className="paint-note">DIGI-TEC is an independent workshop. Manufacturer names identify the vehicles discussed.</p></section>

        <section id="paint-assessment" className="paint-section paint-assessment-section" aria-labelledby="paint-assessment-title"><div><p className="paint-kicker">Start with your car</p><h2 id="paint-assessment-title">Get Paint Assessment &amp; Quote</h2><p>Send your model, year and main concern. You can attach photos in WhatsApp and ask which areas may improve with polishing or paint correction.</p><p>Include a wider panel view and a close-up that shows the marks. An exact quote or correction recommendation may require inspection at the workshop.</p><ContactLink placement="assessment_photos" photo>Send Us Photos on WhatsApp</ContactLink></div><PaintAssessmentForm /></section>

        <section id="paint-faq" className="paint-section" aria-labelledby="paint-faq-title"><p className="paint-kicker">Know what to expect</p><h2 id="paint-faq-title">Car Polishing &amp; Paint Correction FAQs</h2><div className="paint-faqs">{paintFaqs.map((faq) => <details key={faq.question}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</div></section>

        <section id="paint-contact" className="paint-section paint-soft paint-split" aria-labelledby="paint-contact-title"><div><p className="paint-kicker">Car polishing near you in Dubai</p><h2 id="paint-contact-title">Visit DIGI-TEC in Al Quoz</h2><address>DIGI-TEC Performance Center<br />Al Quoz Industrial Area 3<br />Dubai, UAE<br /><a href="tel:+97143402223" data-cta-placement="paint_contact">+971 4 340 2223</a></address></div><div><p>Discuss the paint condition before visiting and confirm current opening hours and appointment availability. The team can advise on the appropriate next assessment.</p><div className="paint-actions"><ContactLink placement="contact" /><a href="tel:+97143402223" data-cta-placement="paint_contact" className="paint-button paint-secondary"><Phone size={18} aria-hidden="true" />Call the workshop</a></div><a href="https://maps.google.com/?q=Al+Quoz+Industrial+Area+3+Dubai" target="_blank" rel="noopener noreferrer" data-cta-placement="paint_location" className="paint-link"><MapPin size={18} aria-hidden="true" />View the workshop area</a><p className="paint-note"><Link to="/services/paint-protection-dubai">Explore paint-care options</Link> or <Link to="/services">all workshop services</Link>.</p></div></section>
      </main>
      <Footer />
      <nav className="paint-mobile-contact" aria-label="Paint assessment contact shortcuts"><a href={PAINT_PHOTO_HREF} target="_blank" rel="noopener noreferrer" data-cta-placement="paint_mobile_photos"><Camera size={19} aria-hidden="true" />Send paint photos</a><a href="tel:+97143402223" data-cta-placement="paint_mobile_call"><Phone size={18} aria-hidden="true" />Call</a></nav>
    </div>
  );
}
