import { useEffect, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { ArrowDown, ArrowUpRight, Check, MapPin, MessageCircle, Phone, TriangleAlert } from 'lucide-react';
import Header from '@/components/Header';
import { Footer } from '@/components/Footer';
import { LocalizedLink as Link } from '@/components/LocalizedLink';
import { useSeo } from '@/hooks/use-seo';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { brands } from '@/data/brands';
import { buildBreadcrumb, buildFAQ, buildService, buildWebPage, pageGraph, SITE_URL } from '@/lib/schema';
import { SUSPENSION_PATH, SUSPENSION_TITLE, SUSPENSION_DESCRIPTION, SUSPENSION_H1, SUSPENSION_INTRO, suspensionWhatsApp, suspensionConcerns, suspensionScope, suspensionProcess, suspensionBrands, suspensionFaqs } from '@/data/suspensionContent';
import suspensionImage from '@/assets/suspension-repair-dubai.jpg';

const url = `${SITE_URL}${SUSPENSION_PATH}`;
const graph = pageGraph([
  buildWebPage({url, name:SUSPENSION_TITLE, description:SUSPENSION_DESCRIPTION, breadcrumbId:`${url}#breadcrumb`, mainEntityId:`${url}#service`, primaryImage:suspensionImage}),
  buildBreadcrumb(url, [{name:'Home',url:'/'},{name:'Services',url:'/services'},{name:SUSPENSION_H1,url}]),
  buildService({url, name:SUSPENSION_H1, serviceType:'Car suspension inspection and repair', description:SUSPENSION_INTRO, image:suspensionImage}),
  buildFAQ(url, suspensionFaqs),
]);

function Enquiry({children, placement, concern}: {children:React.ReactNode; placement:string; concern?:string}) {
  return <a className="susp-button susp-primary" href={suspensionWhatsApp(concern)} target="_blank" rel="noopener noreferrer" data-cta-placement={`suspension_${placement}`}><MessageCircle size={18} aria-hidden="true" />{children}</a>;
}

export default function SuspensionRepairPage() {
  const [selected, setSelected] = useState('noise');
  const {hash} = useLocation();
  useEffect(() => { if (hash) document.getElementById(hash.slice(1))?.scrollIntoView({block:'start',behavior:'instant'}); }, [hash]);
  useSeo({title:SUSPENSION_TITLE, description:SUSPENSION_DESCRIPTION, canonical:url, jsonLd:graph});
  const concern = suspensionConcerns.find(item=>item.id===selected) ?? suspensionConcerns[0];

  return <div className="susp-page"><Header overlay /><main id="main-content">
    <section className="susp-hero susp-shell" aria-labelledby="susp-title">
      <nav className="susp-breadcrumb" aria-label="Breadcrumb"><Link to="/">Home</Link><span>/</span><Link to="/services">Services</Link><span>/</span><span aria-current="page">Suspension repair</span></nav>
      <div className="susp-hero-grid"><div className="susp-hero-copy"><p className="susp-kicker">Ride quality. Control. Confidence.</p><h1 id="susp-title">Car Suspension <br />Repair <span>in Dubai</span></h1><p className="susp-lead">{SUSPENSION_INTRO}</p><div className="susp-actions"><Enquiry placement="hero">Book a Suspension Inspection</Enquiry><a href="#susp-symptoms" className="susp-text-link">Explore your symptoms <ArrowDown size={17} aria-hidden="true" /></a></div><div className="susp-hero-details"><span><MapPin size={16} aria-hidden="true" />Al Quoz Industrial Area 3</span><a href="tel:+97143402223" data-cta-placement="suspension_hero_call"><Phone size={16} aria-hidden="true" />Call DIGI-TEC</a></div></div><figure className="susp-hero-photo"><img src={suspensionImage} width={1600} height={1066} {...{fetchpriority:'high'}} alt="Suspension strut, control arms and brake assembly with the wheel removed" /><figcaption>Suspension detail · components vary by vehicle</figcaption><div className="susp-photo-label"><span>Identify the system</span><span>Inspect the concern</span><span>Agree the repair</span></div></figure></div>
      <div className="susp-intent-strip"><span>Shock absorbers & struts</span><span>Arms, bushes & joints</span><span>Air & adaptive suspension</span></div>
    </section>

    <section id="susp-symptoms" className="susp-section susp-shell" aria-labelledby="susp-symptoms-title"><div className="susp-section-heading"><p className="susp-kicker">Start with what you notice</p><h2 id="susp-symptoms-title">What has changed <br />about your ride?</h2><p>Select the concern closest to yours. These are starting points for an inspection, not a diagnosis.</p></div><div className="susp-concern-layout"><div className="susp-concern-options" role="group" aria-label="Choose a suspension concern">{suspensionConcerns.map(item=><button key={item.id} type="button" id={`susp-choice-${item.id}`} aria-pressed={selected===item.id} aria-controls={`susp-panel-${item.id}`} onClick={()=>setSelected(item.id)}><span><strong>{item.label}</strong><span>{item.short}</span></span><ArrowUpRight size={20} aria-hidden="true" /></button>)}</div><div className="susp-concern-answer" aria-live="polite">{suspensionConcerns.map(item=><div key={item.id} id={`susp-panel-${item.id}`} aria-labelledby={`susp-choice-${item.id}`} hidden={selected!==item.id}><p className="susp-panel-label">Your inspection starts here</p><h3>{item.heading}</h3><p>{item.detail}</p><div className="susp-prompt"><span>Useful details to share</span><p>{item.prompt}</p></div></div>)}<Enquiry placement="selected_concern" concern={concern.enquiry}>Discuss This Concern</Enquiry></div></div><aside className="susp-safety"><TriangleAlert size={21} aria-hidden="true" /><p>If the car is severely low, a tyre is rubbing, control feels unstable or the handbook tells you to stop, stop safely and seek assistance before continuing.</p></aside></section>

    <section id="susp-repairs" className="susp-repairs" aria-labelledby="susp-repairs-title"><div className="susp-shell"><div className="susp-split-heading"><div><p className="susp-kicker">The work your car may need</p><h2 id="susp-repairs-title">Suspension repair, <br />matched to the findings.</h2></div><p>The vehicle specification and inspection determine which components need attention. Your estimate sets out parts, labour and any required follow-up procedures.</p></div><div className="susp-repair-list">{suspensionScope.map((item,index)=><article key={item.title}><span className="susp-repair-number">0{index+1}</span><div><h3>{item.title}</h3><p>{item.detail}</p></div></article>)}</div><p className="susp-small">Coverage and parts availability are confirmed for the exact vehicle. The list describes possible work, not a package automatically applied to every car.</p></div></section>

    <section id="susp-air" className="susp-section susp-shell susp-air" aria-labelledby="susp-air-title"><div><p className="susp-kicker">When ride height changes</p><h2 id="susp-air-title">Air suspension <br />repair in Dubai</h2><p>A car that settles overnight or struggles to change height needs an assessment of the fitted system. Air-spring leaks, lines, valves, compressor performance and height information can be relevant.</p><p>Replacing a visible component without checking the cause may leave the original problem unresolved. We define the relevant tests before agreeing the repair.</p><Link to="/services/mercedes-suspension-repair-dubai" className="susp-text-link">Mercedes AIRMATIC & suspension support <ArrowUpRight size={17} aria-hidden="true" /></Link></div><div className="susp-air-checks"><p className="susp-panel-label">An inspection can connect these checks</p>{[
      ['01','Height & history','Which corner changes, when it happens and what the service history shows.'],
      ['02','Leaks & air paths','Relevant air springs, connections, lines and valve operation.'],
      ['03','Supply & compressor','Pressure supply and compressor operation, where supported.'],
      ['04','Sensors & controls','Height information, wiring and compatible fault or live-data checks.'],
    ].map(([number,title,detail])=><div key={number}><span>{number}</span><div><h3>{title}</h3><p>{detail}</p></div></div>)}<p className="susp-system-note">Air suspension, adaptive damping and hydraulic active suspension are different arrangements. The model, options and installed equipment determine the procedure.</p></div></section>

    <section id="susp-process" className="susp-process" aria-labelledby="susp-process-title"><div className="susp-shell"><p className="susp-kicker">A clear path to the repair</p><h2 id="susp-process-title">Understand. Test. <br />Agree. Repair.</h2><ol>{suspensionProcess.map((step,index)=><li key={step.title}><span aria-hidden="true">0{index+1}</span><h3>{step.title}</h3><p>{step.detail}</p></li>)}</ol><div className="susp-process-end"><p>Start with the symptoms and your vehicle details.</p><Enquiry placement="process">Request a Suspension Assessment</Enquiry></div></div></section>

    <section id="susp-alignment" className="susp-section susp-shell susp-alignment" aria-labelledby="susp-alignment-title"><div><p className="susp-kicker">Repair, alignment or another system?</p><h2 id="susp-alignment-title">Will alignment <br />solve the problem?</h2><p>Wheel alignment concerns geometry. It does not repair a worn joint, damaged control arm, failed damper or leaking air component.</p><p>A pull, vibration or uneven tyre wear can also involve tyres, wheels, steering or other components. Tell us about an impact, recent tyre changes or earlier repairs so the inspection can follow the evidence.</p></div><div className="susp-alignment-notes"><article><Check size={22} aria-hidden="true" /><h3>Repair what the inspection finds</h3><p>Any worn or damaged components that affect the work are considered before the final geometry is set.</p></article><article><Check size={22} aria-hidden="true" /><h3>Confirm the required final procedure</h3><p>Alignment and supported ride-height calibration depend on the vehicle and repair. Neither is assumed for every visit.</p></article><div className="susp-related-links"><Link to="/services/steering-repair-dubai">Steering & rack inspection <ArrowUpRight size={16} aria-hidden="true" /></Link><Link to="/services/tire-repair-dubai">Tyre & wheel concerns <ArrowUpRight size={16} aria-hidden="true" /></Link><Link to="/services/car-diagnostics-dubai">Vehicle diagnostics <ArrowUpRight size={16} aria-hidden="true" /></Link></div></div></section>

    <section id="susp-cost" className="susp-cost" aria-labelledby="susp-cost-title"><div className="susp-shell susp-cost-grid"><div><p className="susp-kicker">A quote with a defined scope</p><h2 id="susp-cost-title">What affects suspension <br />repair cost in Dubai?</h2><p>The same symptom can lead to different repairs. The inspection establishes the fault and the work needed before a final repair estimate is agreed.</p><Enquiry placement="quote" concern="I would like to discuss a suspension inspection and repair estimate.">Ask About Inspection & Repair Cost</Enquiry></div><dl>{[
      ['Vehicle & system','Model, year, fitted conventional, air, adaptive or active equipment.'],
      ['Diagnosis & access','The tests and component access needed to establish the cause.'],
      ['Parts & labour','The confirmed repair, proposed parts option and installation work.'],
      ['Final procedures','Required alignment, supported calibration and agreed verification.'],
    ].map(([term,detail])=><div key={term}><dt>{term}</dt><dd>{detail}</dd></div>)}</dl></div></section>

    <section id="susp-vehicles" className="susp-section susp-shell" aria-labelledby="susp-vehicles-title"><div className="susp-split-heading"><div><p className="susp-kicker">Find your fitted system</p><h2 id="susp-vehicles-title">Suspension support <br />for your vehicle</h2></div><p>Use your brand’s suspension page for model and system context. For other vehicles, send the make, model and year to confirm coverage before booking.</p></div><div className="susp-brand-links">{suspensionBrands.map(brand=><Link key={brand.slug} to={brand.path}><img src={brands.find(item=>item.slug===brand.slug)?.logo} alt="" width={48} height={48} loading="lazy" /><span><strong>{brand.name}</strong><span>Suspension repair</span></span><ArrowUpRight size={18} aria-hidden="true" /></Link>)}</div></section>

    <section id="susp-faq" className="susp-faq-section" aria-labelledby="susp-faq-title"><div className="susp-shell susp-faq-grid"><div><p className="susp-kicker">Before the workshop visit</p><h2 id="susp-faq-title">Your suspension <br />questions, answered.</h2><p>Cost, warning messages, air suspension and what to expect from the inspection.</p></div><Accordion type="single" collapsible className="susp-faq">{suspensionFaqs.map((faq,index)=><AccordionItem key={faq.question} value={`susp-faq-${index}`}><AccordionTrigger>{faq.question}</AccordionTrigger><AccordionContent forceMount><p>{faq.answer}</p></AccordionContent></AccordionItem>)}</Accordion></div></section>

    <section id="susp-booking" className="susp-booking susp-shell" aria-labelledby="susp-booking-title"><div><p className="susp-kicker">Al Quoz · Dubai</p><h2 id="susp-booking-title">Let’s understand <br />what your car needs.</h2><p>Send the vehicle details and what you have noticed. We’ll confirm coverage, the inspection scope and an available appointment.</p><Enquiry placement="booking">Arrange Your Suspension Inspection</Enquiry></div><div className="susp-location"><MapPin size={26} aria-hidden="true" /><h3>DIGI-TEC Performance Center</h3><p>Al Quoz Industrial Area 3 <br />Dubai, UAE</p><a href="https://maps.google.com/?q=Digi-Tec+Performance+Center+Al+Quoz+Industrial+Area+3+Dubai" target="_blank" rel="noopener noreferrer">Get directions <ArrowUpRight size={17} aria-hidden="true" /></a><a href="tel:+97143402223" data-cta-placement="suspension_booking_call">+971 4 340 2223</a></div></section>
  </main><Footer /></div>;
}
