import { LocalizedLink as Link } from '@/components/LocalizedLink';
import { ASTON_HUB_PATH, ASTON_SERVICES, ASTON_WHATSAPP_HREF } from '@/data/astonMartinHubContent';

const Actions = () => <div className="mt-6 flex flex-wrap gap-3"><a className="btn-primary" href={ASTON_WHATSAPP_HREF} target="_blank" rel="noopener noreferrer">Request an Aston Martin Service Quote</a><a className="btn-secondary" href="tel:+97143402223">Call the Al Quoz workshop</a></div>;
export const AstonMartinHubSections = () => <>
  <section className="py-12 sm:py-16 border-t border-white/10"><div className="max-w-7xl mx-auto px-5 sm:px-6 grid gap-8 lg:grid-cols-2"><div><p className="eyebrow">Independent Aston Martin service in Dubai</p><h2 className="text-3xl sm:text-4xl font-black mt-4">Plan the work around your car</h2><p className="text-gray-300 leading-8 mt-5">Whether you need scheduled servicing or help with a warning, start with the model, year and service history. Our Al Quoz workshop reviews the concern, explains the inspection needed and prepares an estimate for your approval.</p><Actions /></div><aside className="card-premium rounded-2xl p-6"><h3 className="text-xl font-bold">Helpful details before booking</h3><ul className="list-disc pl-5 mt-4 space-y-3 text-gray-300"><li>Model and year</li><li>Mileage and service history</li><li>Warning message, symptoms and when they occur</li><li>Preferred appointment time</li></ul><p className="mt-5 text-gray-300">A VIN is not required for the first enquiry. It may be requested later to identify parts or fitted systems.</p><a className="inline-block text-burnt-orange mt-5" href="https://maps.google.com/?q=Al+Quoz+Industrial+Area+3+Dubai" target="_blank" rel="noopener noreferrer">Directions to Al Quoz Industrial Area 3</a></aside></div></section>
  <section className="py-12 sm:py-16 border-t border-white/10"><div className="max-w-7xl mx-auto px-5 sm:px-6"><h2 className="text-3xl sm:text-4xl font-black">Aston Martin maintenance, diagnostics and repair</h2><p className="mt-5 text-gray-300 leading-8">Choose the service that matches your concern for inspection details and quotation factors.</p><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5 mt-8">{ASTON_SERVICES.slice(0,9).map(s=><Link key={s.slug} to={`${ASTON_HUB_PATH}/${s.slug}`} className="card-premium rounded-2xl p-6"><h3 className="text-xl font-bold">{s.title}</h3><p className="mt-4 text-base leading-7 text-gray-300">{s.copy}</p><span className="inline-block mt-5 text-burnt-orange">Explore Aston Martin {s.title.toLowerCase()} →</span></Link>)}</div><h3 className="text-xl font-bold mt-8">Bodywork and other repair enquiries</h3><div className="flex flex-wrap gap-4 mt-4">{ASTON_SERVICES.slice(9).map(s=><Link className="text-burnt-orange underline" key={s.slug} to={`${ASTON_HUB_PATH}/${s.slug}`}>{s.title}</Link>)}</div><Actions /></div></section>
  <section className="py-12 sm:py-16 border-t border-white/10"><div className="max-w-7xl mx-auto px-5 sm:px-6"><h2 className="text-3xl sm:text-4xl font-black">Aston Martin models and owner guidance</h2><div className="grid md:grid-cols-3 gap-6 mt-8">{[
    ['DBX and DBX707','Discuss maintenance, brakes, cooling, gearbox and suspension concerns. DBX707 specifications should not be applied to every DBX variant.'],
    ['Vantage','Identify the generation before discussing gearbox, engine or brake work. Historic Sportshift systems differ from later automatic arrangements.'],
    ['DB11, DB12 and DBS','Service history and the fitted V8 or V12 guide the first inspection. Engine, electronics and parts requirements differ between models and years.'],
  ].map(([name,copy])=><article key={name} className="card-premium rounded-2xl p-6"><h3 className="text-xl font-bold">{name}</h3><p className="mt-4 text-gray-300 leading-7">{copy}</p></article>)}</div><Link className="inline-block mt-6 text-burnt-orange underline" to="/blog/aston-martin-db11-service-dubai-guide">Read the Aston Martin DB11 service guide</Link></div></section>
  <section className="py-12 sm:py-16 border-t border-white/10"><div className="max-w-7xl mx-auto px-5 sm:px-6 grid lg:grid-cols-2 gap-8"><figure><img src="/images/aston-martin-service-dubai-hero.jpg" alt="Aston Martin in the DIGI-TEC workshop" loading="lazy" width="941" height="1672" className="w-full aspect-[4/3] object-cover rounded-2xl" /><figcaption className="mt-3 text-sm text-gray-400">An existing DIGI-TEC workshop photograph. Ask the team about relevant repair examples for your enquiry.</figcaption></figure><div><h2 className="text-3xl font-black">Assessment, quotation and approval</h2><p className="text-gray-300 leading-8 mt-5">Service cost depends on the model, history and items due. Repair estimates also depend on findings, test time, parts and labour. The team explains the proposed work and options before approval.</p><ol className="list-decimal pl-5 space-y-4 mt-5 text-gray-300"><li>Review the vehicle and concern.</li><li>Inspect and test the relevant system.</li><li>Explain findings, parts options and timing.</li><li>Agree the work and appropriate checks afterwards.</li></ol><Link className="inline-block mt-6 text-burnt-orange underline" to="/blog/aston-martin-best-workshop-dubai">How to compare Aston Martin workshops</Link><Actions /></div></div></section>
</>;
