import { ArrowRight, CheckCircle2, MapPin, MessageCircle, Phone } from 'lucide-react';
import { LocalizedLink as Link } from '@/components/LocalizedLink';
import { AUDI_HUB_PATH, AUDI_SECONDARY_SERVICES, AUDI_SERVICES, AUDI_WHATSAPP_HREF } from '@/data/audiHubContent';
import { audiModelPages, audiModelPath } from '@/data/audiModelPages';

const priorityModels = ['a4', 'a6', 'q5', 'q7', 'q8', 'rs3', 'rs6', 'r8'];

export const AudiHubSections = () => <>
  <section className="border-t border-white/5 bg-gradient-to-br from-charcoal/50 to-black py-12 sm:py-16"><div className="mx-auto grid max-w-7xl gap-7 px-4 sm:px-6 lg:grid-cols-[1.15fr_.85fr]"><div><p className="eyebrow mb-4">Independent Audi service in Dubai</p><h2 className="text-3xl font-black sm:text-5xl">Start with the vehicle and the symptom</h2><p className="mt-5 max-w-3xl leading-8 text-gray-300">Audi systems vary by generation, engine, gearbox, quattro layout and option package. DIGI-TEC checks the model, year, mileage, history and concern before confirming the relevant diagnostic access, parts and workshop scope.</p><a data-cta-placement="location_section" href="https://maps.google.com/?q=Al+Quoz+Industrial+Area+3+Dubai" target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex items-center gap-2 font-semibold text-burnt-orange"><MapPin className="h-5 w-5" />Directions to the Al Quoz workshop</a></div><div className="card-premium rounded-2xl p-6"><h3 className="text-xl font-bold">What to send before booking</h3><ul className="mt-4 space-y-3">{['Audi model and year','Mileage and available service history','Exact warning, symptom and when it occurs','Preferred appointment time'].map(item => <li key={item} className="flex gap-3 text-gray-300"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-burnt-orange" />{item}</li>)}</ul><div className="mt-6 flex flex-col gap-3"><a data-cta-placement="details_card" href={AUDI_WHATSAPP_HREF} target="_blank" rel="noopener noreferrer" className="btn-primary"><MessageCircle className="h-5 w-5" />Book an Audi inspection on WhatsApp</a><a data-cta-placement="details_card" href="tel:+97143402223" className="btn-secondary"><Phone className="h-5 w-5" />Call the Al Quoz workshop</a></div></div></div></section>
  <section className="border-t border-white/5 bg-black py-12 sm:py-20" aria-labelledby="audi-services"><div className="mx-auto max-w-7xl px-4 sm:px-6"><p className="eyebrow mb-4">Maintenance, diagnosis and repair</p><h2 id="audi-services" className="text-3xl font-black sm:text-5xl">Audi service areas</h2><p className="mt-5 max-w-3xl leading-8 text-gray-300">This hub owns broad Audi service, repair, workshop and specialist intent. Choose the focused page for the specific work or symptom, so each commercial service keeps a clear search purpose.</p><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{AUDI_SERVICES.map(service => <Link key={service.slug} to={`${AUDI_HUB_PATH}/${service.slug}`} className="card-premium group flex flex-col rounded-2xl p-6"><h3 className="text-xl font-bold group-hover:text-burnt-orange">{service.title}</h3><p className="my-4 text-sm leading-7 text-gray-300">{service.copy}</p><span className="mt-auto inline-flex items-center gap-2 text-sm font-semibold text-burnt-orange">{service.anchor}<ArrowRight className="h-4 w-4" /></span></Link>)}</div><h3 className="mt-10 text-xl font-bold">Other existing Audi service pages</h3><div className="mt-4 flex flex-wrap gap-3">{AUDI_SECONDARY_SERVICES.map(service => <Link key={service.slug} to={`${AUDI_HUB_PATH}/${service.slug}`} className="rounded-full border border-white/15 px-4 py-2 text-sm font-semibold text-gray-200 hover:border-burnt-orange hover:text-burnt-orange">{service.label}</Link>)}</div></div></section>
  <section className="border-t border-white/5 bg-gradient-to-br from-charcoal/40 to-black py-12 sm:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6"><p className="eyebrow mb-4">Model-specific guidance</p><h2 className="text-3xl font-black sm:text-5xl">Audi models with their own service information</h2><p className="mt-5 max-w-3xl leading-8 text-gray-300">Use model pages when the generation, engine, transmission, quattro system or suspension configuration changes the inspection conversation. Every model page links back here for broad Audi service and repair enquiries.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{audiModelPages.filter(model => priorityModels.includes(model.slug)).map(model => <Link key={model.slug} to={audiModelPath(model)} className="card-premium group rounded-2xl p-5"><p className="text-xs font-bold uppercase tracking-widest text-burnt-orange">{model.series}</p><h3 className="mt-2 text-xl font-black group-hover:text-burnt-orange">{model.name}</h3><p className="mt-2 text-sm text-white/55">Service, repair, diagnostics and common concerns.</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-burnt-orange">View {model.name}<ArrowRight className="h-4 w-4" /></span></Link>)}</div><div className="mt-10 card-premium rounded-2xl p-6 sm:p-8"><p className="eyebrow mb-4">Inspection, estimate and approval</p><h2 className="text-2xl font-black sm:text-4xl">A clear repair process before work begins</h2><ol className="mt-5 grid gap-4 text-gray-300 sm:grid-cols-3"><li><strong className="text-white">1. Identify:</strong> confirm the vehicle, systems, history and concern.</li><li><strong className="text-white">2. Assess:</strong> use appropriate diagnostic and physical checks.</li><li><strong className="text-white">3. Agree:</strong> explain findings, parts and scope before approval.</li></ol><div className="mt-6 flex flex-wrap gap-4"><Link to="/best-audi-workshop-dubai" className="inline-flex items-center gap-2 font-semibold text-burnt-orange">How to choose an Audi workshop<ArrowRight className="h-4 w-4" /></Link><Link to="/blog/audi-maintenance-guide-dubai" className="inline-flex items-center gap-2 font-semibold text-burnt-orange">Read the Audi maintenance guide<ArrowRight className="h-4 w-4" /></Link></div></div></div></section>
</>;
