import { ArrowRight, CheckCircle2, MapPin, MessageCircle, Phone } from 'lucide-react';
import { LocalizedLink as Link } from '@/components/LocalizedLink';
import { LAMBORGHINI_HUB_PATH, LAMBORGHINI_SECONDARY_SERVICES, LAMBORGHINI_SERVICES, LAMBORGHINI_WHATSAPP_HREF } from '@/data/lamborghiniHubContent';
import lamborghiniUrusWorkshop from '@/assets/lamborghini-urus-workshop-dubai.jpg';

const modelGroups = [
  { name: 'Urus', models: 'Urus, Urus S and Urus Performante', copy: 'Service, brakes, cooling, low-voltage electrical, eight-speed automatic and model-specific suspension enquiries can be discussed. Urus S adaptive air suspension should not be assumed for every variant.', links: [['Urus owner guide','/blog/lamborghini-urus-service-dubai-guide'],['Urus suspension assessment',`${LAMBORGHINI_HUB_PATH}/suspension-repair`]] },
  { name: 'Huracán', models: 'Huracán, EVO, Tecnica, STO and Sterrato', copy: 'The Huracán EVO uses a seven-speed LDF dual-clutch transmission. Maintenance, warning-light, brake, lift and gearbox concerns still require exact model and fitted-system confirmation.', links: [['Huracán gearbox assessment',`${LAMBORGHINI_HUB_PATH}/transmission-repair`],['Engine diagnostics',`${LAMBORGHINI_HUB_PATH}/engine-diagnostics`]] },
  { name: 'Aventador', models: 'Aventador, S, SV and SVJ', copy: 'Aventador SVJ uses an ISR gearbox rather than the Huracán LDF. Clutch, hydraulic, lift and suspension discussions must be tied to the exact vehicle and accepted workshop capability.', links: [['Aventador transmission assessment',`${LAMBORGHINI_HUB_PATH}/transmission-repair`],['Mechanical assessment',`${LAMBORGHINI_HUB_PATH}/mechanical-repair`]] },
] as const;

export const LamborghiniHubSections = () => <>
  <section className="border-t border-white/5 bg-gradient-to-br from-charcoal/50 to-black py-12 sm:py-16"><div className="mx-auto grid max-w-7xl gap-7 px-4 sm:px-6 lg:grid-cols-[1.15fr_.85fr]"><div><p className="eyebrow mb-4">Independent Lamborghini service in Dubai</p><h2 className="text-3xl font-black sm:text-5xl">Identify the vehicle before defining the work</h2><p className="mt-5 max-w-3xl leading-8 text-gray-300">The badge alone does not define the correct gearbox, suspension, battery or maintenance procedure. DIGI-TEC reviews the model, year, mileage, history and concern, then confirms diagnostic access, parts and available workshop scope.</p><a data-cta-placement="location_section" href="https://maps.google.com/?q=Al+Quoz+Industrial+Area+3+Dubai" target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex items-center gap-2 font-semibold text-burnt-orange"><MapPin className="h-5 w-5"/>Directions to the Al Quoz workshop</a></div><div className="card-premium rounded-2xl p-6"><h3 className="text-xl font-bold">What to send before booking</h3><ul className="mt-4 space-y-3">{['Lamborghini model and year','Mileage and available service history','Exact warning, symptom and when it occurs','Preferred appointment time'].map(item=><li key={item} className="flex gap-3 text-gray-300"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-burnt-orange"/>{item}</li>)}</ul><div className="mt-6 flex flex-col gap-3"><a data-cta-placement="details_card" href={LAMBORGHINI_WHATSAPP_HREF} target="_blank" rel="noopener noreferrer" className="btn-primary"><MessageCircle className="h-5 w-5"/>Request a Lamborghini Assessment</a><a data-cta-placement="details_card" href="tel:+97143402223" className="btn-secondary"><Phone className="h-5 w-5"/>Call the Workshop</a></div></div></div></section>
  <section className="border-t border-white/5 bg-black py-12 sm:py-20" aria-labelledby="lamborghini-services"><div className="mx-auto max-w-7xl px-4 sm:px-6"><p className="eyebrow mb-4">Maintenance, diagnosis and repair</p><h2 id="lamborghini-services" className="text-3xl font-black sm:text-5xl">Lamborghini service areas</h2><p className="mt-5 max-w-3xl leading-8 text-gray-300">Use the focused page that matches the work or symptom. This hub owns broad Lamborghini service, repair, workshop and specialist intent without duplicating every child page.</p><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{LAMBORGHINI_SERVICES.map(service=><Link key={service.slug} to={`${LAMBORGHINI_HUB_PATH}/${service.slug}`} className="card-premium group flex flex-col rounded-2xl p-6"><h3 className="text-xl font-bold group-hover:text-burnt-orange">{service.title}</h3><p className="my-4 text-sm leading-7 text-gray-300">{service.copy}</p><span className="mt-auto inline-flex items-center gap-2 text-sm font-semibold text-burnt-orange">{service.anchor}<ArrowRight className="h-4 w-4"/></span></Link>)}</div><h3 className="mt-10 text-xl font-bold">Other existing Lamborghini service pages</h3><div className="mt-4 flex flex-wrap gap-3">{LAMBORGHINI_SECONDARY_SERVICES.map(service=><Link key={service.slug} to={`${LAMBORGHINI_HUB_PATH}/${service.slug}`} className="rounded-full border border-white/15 px-4 py-2 text-sm font-semibold text-gray-200 hover:border-burnt-orange hover:text-burnt-orange">{service.label}</Link>)}</div></div></section>
  <section className="border-t border-white/5 bg-gradient-to-br from-charcoal/40 to-black py-12 sm:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6"><p className="eyebrow mb-4">Model-specific guidance</p><h2 className="text-3xl font-black sm:text-5xl">Urus, Huracán and Aventador are not interchangeable</h2><div className="mt-9 grid gap-5 lg:grid-cols-3">{modelGroups.map(group=><article key={group.name} className="card-premium rounded-2xl p-6"><p className="text-xs font-bold uppercase tracking-widest text-burnt-orange">{group.name}</p><h3 className="mt-2 text-xl font-bold">{group.models}</h3><p className="mt-4 text-sm leading-7 text-gray-300">{group.copy}</p><div className="mt-5 space-y-2">{group.links.map(([label,path])=><Link key={path} to={path} className="flex items-center gap-2 text-sm font-semibold text-burnt-orange">{label}<ArrowRight className="h-4 w-4"/></Link>)}</div></article>)}</div></div></section>
  <section className="border-t border-white/5 bg-black py-12 sm:py-20"><div className="mx-auto grid max-w-7xl gap-8 px-4 sm:px-6 lg:grid-cols-2"><figure className="overflow-hidden rounded-2xl border border-white/10"><img src={lamborghiniUrusWorkshop} alt="Lamborghini Urus on a lift inside the DIGI-TEC workshop in Al Quoz, Dubai" loading="lazy" width="1086" height="1448" className="aspect-[4/3] w-full object-cover"/><figcaption className="p-5 text-sm text-gray-300">A Lamborghini Urus in the DIGI-TEC workshop. The image supports the facility context and does not claim a particular repair outcome.</figcaption></figure><div><p className="eyebrow mb-4">Inspection, estimate and approval</p><h2 className="text-3xl font-black sm:text-4xl">Service cost follows the confirmed scope</h2><ol className="mt-6 space-y-5 text-gray-300"><li><strong className="text-white">1. Identify:</strong> confirm the vehicle, fitted system, history and concern.</li><li><strong className="text-white">2. Assess:</strong> combine compatible data with suitable physical tests.</li><li><strong className="text-white">3. Estimate:</strong> explain findings, proposed parts, scope and timing before approval.</li></ol><div className="mt-7 flex flex-wrap gap-4"><Link to="/best-lamborghini-workshop-dubai" className="inline-flex items-center gap-2 font-semibold text-burnt-orange">How to compare a Lamborghini workshop<ArrowRight className="h-4 w-4"/></Link><Link to="/blog/lamborghini-maintenance-guide-dubai" className="inline-flex items-center gap-2 font-semibold text-burnt-orange">Read the maintenance guide<ArrowRight className="h-4 w-4"/></Link></div></div></div></section>
</>;
