import { ArrowRight, CheckCircle2, MapPin, MessageCircle, Phone } from 'lucide-react';
import { LocalizedLink as Link } from '@/components/LocalizedLink';
import { MCLAREN_HUB_PATH, MCLAREN_MODEL_GROUPS, MCLAREN_SECONDARY_SERVICES, MCLAREN_SERVICES, MCLAREN_WHATSAPP_HREF } from '@/data/mclarenHubContent';
import workshopLifts from '@/assets/digitec-workshop-lifts.jpg';

export const MclarenHubSections = () => (
  <>
    <section className="border-t border-white/5 bg-gradient-to-br from-charcoal/50 to-black py-12 sm:py-16">
      <div className="mx-auto grid max-w-7xl gap-8 px-4 sm:px-6 lg:grid-cols-[1.1fr_.9fr]">
        <div><p className="eyebrow mb-4">Independent McLaren servicing in Dubai</p><h2 className="text-3xl font-black sm:text-5xl">Start with the vehicle and the concern</h2><p className="mt-5 text-base leading-relaxed text-gray-300">Our Al Quoz workshop reviews the model, VIN, history and symptoms before confirming diagnostic access, parts or repair scope. This matters across conventional V8 and Artura hybrid platforms, and across different transmission and suspension systems.</p><a data-cta-placement="location_section" href="https://maps.google.com/?q=Al+Quoz+Industrial+Area+3+Dubai" target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-burnt-orange"><MapPin className="h-5 w-5" /> Directions to the Al Quoz workshop</a></div>
        <div className="card-premium rounded-2xl p-6"><h3 className="text-xl font-bold">What to send</h3><ul className="mt-4 space-y-3">{['McLaren model and year','Mileage and available service history','Exact warning, symptom and when it occurs','Preferred appointment time'].map(x=><li key={x} className="flex gap-3 text-gray-300"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-burnt-orange" />{x}</li>)}</ul><div className="mt-6 flex flex-col gap-3"><a data-cta-placement="details_card" className="btn-primary" href={MCLAREN_WHATSAPP_HREF} target="_blank" rel="noopener noreferrer"><MessageCircle className="h-5 w-5" /> Request a McLaren assessment</a><a data-cta-placement="details_card" className="btn-secondary" href="tel:+97143402223"><Phone className="h-5 w-5" /> Call the workshop</a></div></div>
      </div>
    </section>
    <section className="border-t border-white/5 bg-black py-12 sm:py-20" aria-labelledby="mclaren-services"><div className="mx-auto max-w-7xl px-4 sm:px-6"><p className="eyebrow mb-4">Service, diagnosis and repair</p><h2 id="mclaren-services" className="text-3xl font-black sm:text-5xl">McLaren workshop services in Dubai</h2><p className="mt-5 max-w-3xl text-base leading-relaxed text-gray-300">Choose the page that matches the work or symptom. This hub covers broad McLaren service, repair, maintenance and independent-workshop intent; the existing service pages provide the detailed assessment path.</p><div className="mt-9 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{MCLAREN_SERVICES.map(s=><Link key={s.slug} to={`${MCLAREN_HUB_PATH}/${s.slug}`} className="card-premium group flex flex-col rounded-2xl p-6"><h3 className="text-xl font-bold group-hover:text-burnt-orange">{s.title}</h3><p className="my-4 text-sm leading-relaxed text-gray-300">{s.copy}</p><span className="mt-auto inline-flex items-center gap-2 text-sm font-semibold text-burnt-orange">{s.anchor}<ArrowRight className="h-4 w-4" /></span></Link>)}</div><h3 className="mt-10 text-xl font-bold">Other existing McLaren service pages</h3><div className="mt-4 flex flex-wrap gap-3">{MCLAREN_SECONDARY_SERVICES.map(s=><Link key={s.slug} to={`${MCLAREN_HUB_PATH}/${s.slug}`} className="rounded-full border border-white/15 px-4 py-2 text-sm font-semibold text-gray-200 hover:border-burnt-orange hover:text-burnt-orange">{s.label}</Link>)}</div><div className="mt-9 flex flex-col items-start justify-between gap-5 rounded-2xl border border-burnt-orange/25 bg-burnt-orange/5 p-6 sm:flex-row sm:items-center"><div><h3 className="text-xl font-bold">Not sure which service matches the warning?</h3><p className="mt-2 max-w-2xl text-sm leading-relaxed text-gray-300">Send the exact warning or symptom. The message requests an assessment; the workshop will confirm the suitable first step and appointment availability.</p></div><a data-cta-placement="services_section" className="btn-primary shrink-0" href={MCLAREN_WHATSAPP_HREF} target="_blank" rel="noopener noreferrer"><MessageCircle className="h-5 w-5" /> Ask about McLaren diagnostics</a></div></div></section>
    <section className="border-t border-white/5 bg-gradient-to-br from-charcoal/40 to-black py-12 sm:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6"><p className="eyebrow mb-4">Confirmed service scope first</p><h2 className="text-3xl font-black sm:text-5xl">McLaren models owners can ask us about</h2><p className="mt-5 max-w-3xl text-base leading-relaxed text-gray-300">Share the exact model and year so the team can identify the fitted systems and suitable first assessment. Engine, transmission, suspension and diagnostic requirements vary across McLaren generations.</p><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{MCLAREN_MODEL_GROUPS.map(group=><article key={group.name} className="card-premium rounded-2xl p-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-burnt-orange">{group.name}</p><h3 className="mt-3 text-lg font-bold">{group.models}</h3><p className="mt-3 text-sm leading-relaxed text-gray-300">{group.copy}</p></article>)}</div></div></section>
    <section className="border-t border-white/5 bg-black py-12 sm:py-20"><div className="mx-auto grid max-w-7xl gap-8 px-4 sm:px-6 lg:grid-cols-2"><figure className="overflow-hidden rounded-2xl border border-white/10"><img src={workshopLifts} alt="DIGI-TEC service bays and vehicle lifts at the Al Quoz workshop in Dubai" loading="lazy" width="1086" height="1448" className="aspect-[4/3] w-full object-cover"/><figcaption className="p-5 text-sm text-gray-300">The DIGI-TEC workshop floor in Al Quoz. This is genuine workshop context and is not presented as a McLaren repair case study.</figcaption></figure><div><p className="eyebrow mb-4">Assessment, estimate and approval</p><h2 className="text-3xl font-black sm:text-4xl">McLaren service costs depend on the vehicle and findings</h2><p className="mt-5 leading-relaxed text-gray-300">Model, year, mileage, history, requested work, diagnostic time, parts, fluids and inspection findings can all affect the estimate. A repair price or completion time cannot be confirmed responsibly before the required assessment.</p><ol className="mt-6 space-y-5 text-gray-300"><li><strong className="text-white">1. Identify:</strong> confirm the vehicle, fitted system and reported concern.</li><li><strong className="text-white">2. Assess:</strong> combine available diagnostic data with appropriate physical testing.</li><li><strong className="text-white">3. Quote:</strong> explain findings, proposed parts, workshop scope and timing before owner approval.</li></ol><div className="mt-7 flex flex-col gap-3 sm:flex-row"><a data-cta-placement="quote_section" className="btn-primary" href={MCLAREN_WHATSAPP_HREF} target="_blank" rel="noopener noreferrer"><MessageCircle className="h-5 w-5" /> Request a McLaren service quote</a><Link to="/blog/mclaren-best-workshop-dubai" className="btn-secondary">Compare a McLaren workshop <ArrowRight className="h-4 w-4" /></Link></div></div></div></section>
  </>
);
