// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_contact_info_default = defineTool({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Return Digitec Performance Center contact details: phone, WhatsApp, email, address, and website.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      business: "Digitec Performance Center",
      phone: "+971 4 340 2223",
      whatsapp: "+971 4 340 2223",
      whatsapp_link: "https://wa.me/97143402223",
      website: "https://digitecme.com",
      area: "Al Quoz Industrial Area, Dubai, UAE",
      specialization: "Independent workshop for German and luxury cars: Mercedes-Benz, BMW, Audi, Porsche, Bentley, Ferrari, Lamborghini, McLaren, Rolls-Royce, Aston Martin, Land Rover, Maybach, Bugatti."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var SITE = "https://digitecme.com";
var services = [
  { slug: "mercedes-repair-dubai", title: "Mercedes Repair in Dubai", category: "mercedes" },
  { slug: "mercedes-mechanical-repair-dubai", title: "Mercedes Mechanical Repair in Dubai", category: "mercedes" },
  { slug: "mercedes-transmission-repair-dubai", title: "Mercedes Transmission Repair in Dubai", category: "mercedes" },
  { slug: "mercedes-suspension-repair-dubai", title: "Mercedes Suspension Repair in Dubai", category: "mercedes" },
  { slug: "mercedes-steering-repair-dubai", title: "Mercedes Steering Repair in Dubai", category: "mercedes" },
  { slug: "mercedes-brake-repair-dubai", title: "Mercedes Brake Repair in Dubai", category: "mercedes" },
  { slug: "mercedes-service-dubai", title: "Mercedes Service in Dubai", category: "mercedes" },
  { slug: "mercedes-oil-change-dubai", title: "Mercedes Oil Change in Dubai", category: "mercedes" },
  { slug: "mercedes-tire-repair-dubai", title: "Mercedes Tire Repair in Dubai", category: "mercedes" },
  { slug: "mercedes-battery-replacement-dubai", title: "Mercedes Battery Replacement in Dubai", category: "mercedes" },
  { slug: "mercedes-exhaust-repair-dubai", title: "Mercedes Exhaust Repair in Dubai", category: "mercedes" },
  { slug: "mercedes-diagnostics-dubai", title: "Mercedes Diagnostics in Dubai", category: "mercedes" },
  { slug: "mercedes-electrical-repair-dubai", title: "Mercedes Electrical Repair in Dubai", category: "mercedes" },
  { slug: "mercedes-fuel-system-repair-dubai", title: "Mercedes Fuel System Repair in Dubai", category: "mercedes" },
  { slug: "mercedes-ac-repair-dubai", title: "Mercedes AC Repair in Dubai", category: "mercedes" },
  { slug: "mercedes-body-repair-dubai", title: "Mercedes Body Repair in Dubai", category: "mercedes" },
  { slug: "mechanical-repair-dubai", title: "Mechanical Repair in Dubai", category: "general" },
  { slug: "transmission-repair-dubai", title: "Transmission Repair in Dubai", category: "general" },
  { slug: "suspension-repair-dubai", title: "Suspension Repair in Dubai", category: "general" },
  { slug: "steering-repair-dubai", title: "Steering Repair in Dubai", category: "general" },
  { slug: "brake-repair-dubai", title: "Brake Repair in Dubai", category: "general" },
  { slug: "car-service-dubai", title: "Car Service in Dubai", category: "general" },
  { slug: "oil-change-dubai", title: "Oil Change in Dubai", category: "general" },
  { slug: "tire-repair-dubai", title: "Tire Repair in Dubai", category: "general" },
  { slug: "battery-replacement-dubai", title: "Battery Replacement in Dubai", category: "general" },
  { slug: "exhaust-repair-dubai", title: "Exhaust Repair in Dubai", category: "general" },
  { slug: "car-diagnostics-dubai", title: "Car Diagnostics in Dubai", category: "general" },
  { slug: "auto-electrical-repair-dubai", title: "Auto Electrical Repair in Dubai", category: "general" },
  { slug: "fuel-system-repair-dubai", title: "Fuel System Repair in Dubai", category: "general" },
  { slug: "car-ac-repair-dubai", title: "Car AC Repair in Dubai", category: "general" },
  { slug: "car-body-repair-dubai", title: "Car Body Repair in Dubai", category: "general" },
  { slug: "paint-protection-dubai", title: "Paint Protection (PPF & Ceramic) in Dubai", category: "general" }
];
var list_services_default = defineTool2({
  name: "list_services",
  title: "List services",
  description: "List Digitec Performance Center services in Dubai. Optionally filter by category (general or mercedes) or a case-insensitive search string on the title.",
  inputSchema: {
    category: z.enum(["general", "mercedes", "all"]).optional().describe("Filter by service category. Defaults to all."),
    search: z.string().optional().describe("Case-insensitive substring to match against the service title.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, search }) => {
    const cat = category ?? "all";
    const q = search?.trim().toLowerCase();
    const filtered = services.filter((s) => cat === "all" || s.category === cat).filter((s) => !q || s.title.toLowerCase().includes(q)).map((s) => ({ ...s, url: `${SITE}/services/${s.slug}` }));
    return {
      content: [{ type: "text", text: JSON.stringify(filtered, null, 2) }],
      structuredContent: { count: filtered.length, services: filtered }
    };
  }
});

// src/lib/mcp/tools/list-brands.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var SITE2 = "https://digitecme.com";
var brands = [
  { name: "Mercedes-Benz", slug: "mercedes-benz-service-dubai" },
  { name: "Maybach", slug: "maybach-service-dubai" },
  { name: "Porsche", slug: "porsche-service-dubai" },
  { name: "Audi", slug: "audi-service-dubai" },
  { name: "BMW", slug: "bmw-service-dubai" },
  { name: "Lamborghini", slug: "lamborghini-service-dubai" },
  { name: "Bentley", slug: "bentley-service-dubai" },
  { name: "McLaren", slug: "mclaren-service-dubai" },
  { name: "Ferrari", slug: "ferrari-service-dubai" },
  { name: "Bugatti", slug: "bugatti-service-dubai" },
  { name: "Land Rover", slug: "land-rover-service-dubai" },
  { name: "Rolls-Royce", slug: "rolls-royce-service-dubai" },
  { name: "Aston Martin", slug: "aston-martin-service-dubai" }
];
var list_brands_default = defineTool3({
  name: "list_brands",
  title: "List brands serviced",
  description: "List luxury and performance car brands serviced by Digitec Performance Center in Dubai.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = brands.map((b) => ({ ...b, url: `${SITE2}/brands/${b.slug}` }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { count: items.length, brands: items }
    };
  }
});

// src/lib/mcp/tools/build-booking-link.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var build_booking_link_default = defineTool4({
  name: "build_booking_link",
  title: "Build WhatsApp booking link",
  description: "Build a WhatsApp deep link to Digitec Performance Center with a prefilled booking message that includes the car and service context.",
  inputSchema: {
    vehicle: z2.string().min(1).describe("Vehicle make and model, e.g. 'Mercedes C63 AMG 2020'."),
    service: z2.string().min(1).describe("Service the customer wants, e.g. 'Oil change' or 'AIRMATIC suspension fault'."),
    notes: z2.string().optional().describe("Optional extra context like symptoms, mileage, or preferred date.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: false },
  handler: ({ vehicle, service, notes }) => {
    const lines = [
      `Hi Digitec, I'd like to book a service.`,
      `Vehicle: ${vehicle}`,
      `Service: ${service}`
    ];
    if (notes) lines.push(`Notes: ${notes}`);
    const message = lines.join("\n");
    const url = `https://wa.me/97143402223?text=${encodeURIComponent(message)}`;
    return {
      content: [{ type: "text", text: url }],
      structuredContent: { whatsapp_url: url, message }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "digitec-mcp",
  title: "Digitec Performance Center",
  version: "0.1.0",
  instructions: "Tools for Digitec Performance Center, an independent Dubai workshop for German and luxury cars. Use `list_services` to discover service pages, `list_brands` for supported brands, `get_contact_info` for phone/WhatsApp/location, and `build_booking_link` to generate a prefilled WhatsApp booking URL.",
  tools: [get_contact_info_default, list_services_default, list_brands_default, build_booking_link_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
